#!/bin/sh
# $Id: mkdist 149 2008-11-03 18:51:28Z dtrg $
# $HeadURL: https://wordgrinder.svn.sf.net/svnroot/wordgrinder/wordgrinder/mkdist $
# $LastChangedDate: 2007-10-05 00:12:15 +0100 (Fri, 05 Oct 2007) $
#
# Script to build a distribution package.

set -e

PACKAGE=olua
	
if [ "$1" = "" ]; then
	echo "Please specify a version number!"
	exit 1
fi

if [ -d ../$PACKAGE-$1 ]; then
	echo "I think you've already generated version $1."
	exit 1
fi

mkdir ../$PACKAGE-$1
cp -v -a --parents \
	./COPYING \
	./README \
	./doc/documentation.wg \
	./doc/language-overview.html \
	./doc/runtime.html \
	./doc/summary.html \
	./doc/oldot/* \
	./example.olua \
	./oldot \
	./olua/app/application.olua \
	./olua/app/argumentparser.olua \
	./olua/app/init.olua \
	./olua/init.lua \
	./olua/lexer.lua \
	./olua/lib/exception.olua \
	./olua/lib/init.olua \
	./olua/lib/invocation.olua \
	./olua/lib/object.olua \
	./olua/lib/proxy.olua \
	./olua/parser.lua \
	./olua/transform.lua \
	./olua/unparser.lua \
	./oluac \
	./rebuild-documentation \
	./run-tests \
	./test/_framework.olua \
	./test/cinheritance.olua \
	./test/exceptions.olua \
	./test/oinheritance.olua \
	./test/omethods.olua \
	./test/proxy.olua \
	./tools/oldot.olua \
	./tools/oluac.lua \
	./tools/oluarun.lua \
	./tools/run-tests.lua \
	\
	../$PACKAGE-$1

(cd .. && tar cvf $PACKAGE-$1.tar.bz2 --bzip2 $PACKAGE-$1) && rm -rf ../$PACKAGE-$1

echo ""
echo "Done --- but did you remember to update the version number in the README?"
